language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t jeremyroa/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jeremyroa/docker-react npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "learn-docker-react"
  env: "LearnDockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-522311202216 "
  bucket_path: "learn-docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY